import { customerData } from "@/Data";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/customerDetail.module.css";
import Image from "next/image";
import Head from "next/head";
import Grid from "@mui/material/Grid";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

function CustomerDetail() {
  const router = useRouter();
  const [currentCustomer, setCurrentCustomer] = useState(null);
  const [activeFilter, setActiveFilter] = useState("Monthly");
  const [mostLikedFilter, setMostLikedFilter] = useState("Monthly");

  useEffect(() => {
    if (router.query.id) {
      setCurrentCustomer(customerData.find((o) => o.id === router.query.id));
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>
          {currentCustomer ? "Customer ID: " + currentCustomer.id : "Customer not found"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentCustomer ? (
        <div className={styles["container"]}>
          <div className={styles["cusDetailHead"]}>
            <h1>Customer Detail</h1>
            <p>Here your Customer Detail Profile</p>
          </div>
          <Grid container spacing={4} sx={{ alignItems: "center" }}>
            <Grid size={8}>
              <div className={styles["userAbout"]}>
                {/* <Image src={} alt="" width={} height={}/> */}
                <div
                  style={{
                    width: "222px",
                    height: "222px",
                    borderRadius: "22px",
                    backgroundColor: "gray",
                  }}
                ></div>
                <div className={styles["names"]}>
                  <div className={styles["namesHead"]}>
                    <div className={styles["nameAndLoc"]}>
                      <h3>{currentCustomer.name}</h3>
                      <p>{currentCustomer.job}</p>
                      <p>{currentCustomer.homeLocation}</p>
                    </div>
                    <div className={styles["btns"]}>
                      <button>
                        <Image src="/question.png" alt="" width={28} height={28} />
                      </button>
                      <button>
                        <Image src="/edit.png" alt="" width={28} height={28} />
                      </button>
                    </div>
                  </div>
                  <div className={styles["namesFooter1"]}>
                    <div className={styles["emailNumJob"]}>
                      <button>
                        <Image src="/email.png" alt="" width={20} height={20} />
                      </button>
                      <p>{currentCustomer.email}</p>
                    </div>
                    <div className={styles["emailNumJob1"]}>
                      <button>
                        <Image src="/emailPhone.png" alt="" width={20} height={20} />
                      </button>
                      <p>{currentCustomer.phone}</p>
                    </div>
                    <div className={styles["emailNumJob2"]}>
                      <button>
                        <Image src="/job.png" alt="" width={20} height={20} />
                      </button>
                      <p>{currentCustomer.companyName}</p>
                    </div>
                  </div>
                </div>
              </div>
            </Grid>
            <Grid size={4}>
              <div className={styles["cartAbout"]}>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    color: "white",
                    padding: "0px 36px 0px 38px",
                  }}
                >
                  <p>Your Balance</p>
                  <button
                    style={{
                      background: "unset",
                      border: "none",
                      cursor: "pointer",
                    }}
                  >
                    <Image src="/dot.png" alt="" width={31} height={25} />
                  </button>
                </div>
                <p
                  style={{
                    fontSize: "52px",
                    color: "white",
                    padding: "10px 36px 10px 38px",
                  }}
                >
                  $ {currentCustomer.userCard.cardBalans}
                </p>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    color: "white",
                    fontSize: "21px",
                    padding: "0px 36px 26px 38px",
                    marginBottom: "10px",
                  }}
                >
                  <p>{currentCustomer.userCard.cardNumber}</p>
                  <p>{currentCustomer.userCard.cardDate}</p>
                </div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    backgroundColor: "#40134726",
                    width: "100%",
                    padding: "21px 36px 18px 38px",
                  }}
                >
                  <div className={styles["cardName"]}>
                    <p>Name</p>
                    <p>{currentCustomer.userCard.cardName}</p>
                  </div>
                  <Image src="/mastercard.png" alt="" width={60} height={56} />
                </div>
              </div>
            </Grid>
          </Grid>
          <div className={styles["cusDetailFooter"]}>
            <div className={styles["mostOrderedFood"]}>
              <div className={styles["btnAndName"]}>
                <div className={styles["mostOrdered"]}>
                  <p>Most Ordered Food</p>
                  <p>Lorem ipsum dolor sit amet, consectetur</p>
                </div>
                <div className={styles["mostOrderBtns"]}>
                  <button
                    className={activeFilter === "Monthly" ? styles.active : ""}
                    onClick={() => setActiveFilter("Monthly")}
                  >
                    Monthly
                  </button>
                  <button
                    className={activeFilter === "Weekly" ? styles.active : ""}
                    onClick={() => setActiveFilter("Weekly")}
                  >
                    Weekly
                  </button>
                  <button
                    className={activeFilter === "Daily" ? styles.active : ""}
                    onClick={() => setActiveFilter("Daily")}
                  >
                    Daily
                  </button>
                </div>
              </div>
              {currentCustomer.items.map((item) => (
                <Order key={currentCustomer.id} item={item} />
              ))}
            </div>
            <div className={styles["mostLokedFood"]}>
              <div className={styles["btnAndName"]}>
                <div className={styles["mostOrdered"]}>
                  <p>Most Liked Food</p>
                  <p>Lorem ipsum dolor sit amet, consectetur</p>
                </div>
                <div className={styles["mostOrderBtns"]}>
                  <button
                    className={mostLikedFilter === "Monthly" ? styles.active : ""}
                    onClick={() => setMostLikedFilter("Monthly")}
                  >
                    Monthly
                  </button>
                  <button
                    className={mostLikedFilter === "Weekly" ? styles.active : ""}
                    onClick={() => setMostLikedFilter("Weekly")}
                  >
                    Weekly
                  </button>
                  <button
                    className={mostLikedFilter === "Daily" ? styles.active : ""}
                    onClick={() => setMostLikedFilter("Daily")}
                  >
                    Daily
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div>
          <p>Customer not found</p>
        </div>
      )}
    </>
  );
}

export default CustomerDetail;

function Order(props) {
  const { item } = props;
  return (
    <div
      style={{
        padding: "12px 30px",
        width: "100%",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
      }}
    >
      {/* <Image src="" alt="" width={} height={} /> */}
      <div style={{ display: "flex" }}>
        <div
          style={{
            borderRadius: "16px",
            background: "#B9BBBD",
            width: "87px",
            height: "87px",
          }}
        ></div>
        <div className={styles["middle"]}>
          <p>{item.foodName}</p>
          <p>{item.food}</p>
          <p>
            Serves for {item.person} Person | {item.min}mins
          </p>
        </div>
      </div>
      <div className={styles["priceBtn"]}>
        <p>${item.price}</p>
        <button
          style={{
            background: "unset",
            border: "none",
            marginLeft: "32px",
            cursor: "pointer",
          }}
        >
          <Image src="/dotBlack.png" alt="" width={24} height={24} />
        </button>
      </div>
    </div>
  );
}

CustomerDetail.getLayout = (pageProps) => (
  <MainLayout>
    <CustomerDetail {...pageProps} />
  </MainLayout>
);
