import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Ordered from "./components/ordered";
export default function order() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;700&display=swap"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Ordered />
      </div>
    </>
  );
}
