import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import FoodsList from "@/components/pages/foods/FoodsList";
export default function Foods() {
  return (
    <>
      <Head>
        <title>Foods List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <FoodsList />
      </>
    </>
  );
}

Foods.getLayout = (pageProps) => (
  <MainLayout>
    <Foods {...pageProps} />
  </MainLayout>
);
