import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import TextField from "@mui/material/TextField";
import { GoEye } from "react-icons/go";

export default function New() {
  return (
    <>
      <Head>
        <title>New Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <form
          style={{
            maxWidth: "400px",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <TextField
            id="outlined-basic"
            label="Name"
            variant="outlined"
            sx={{ marginBottom: "15px" }}
          />
          <TextField
            id="outlined-basic"
            label="Price"
            variant="outlined"
            sx={{ marginBottom: "15px" }}
          />
          <TextField
            id="outlined-basic"
            label="Image"
            variant="outlined"
            sx={{ marginBottom: "15px" }}
          />

          <button style={{ margin: "0 auto", padding: "10px 50px" }}>
            Add
          </button>
        </form>
      </div>
    </>
  );
}

New.getLayout = (pageProps) => (
  <MainLayout>
    <New {...pageProps} />
  </MainLayout>
);
