import { orderListData as d } from "@/pages/Data";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/orderDetail.module.css";
import Image from "next/image";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Link from "next/link";

function OrderDetail() {
  const router = useRouter();
  const [currentOrder, setCurrentOrder] = useState(null);
  const [tableItems, setTableItems] = useState([]);

  useEffect(() => {
    if (router.query.id) {
      const orderItem = d.find((o) => o.id === router.query.id)
      if (orderItem) {
        setCurrentOrder(orderItem);
        setTableItems(orderItem.items)
      }

    }
  }, [router]);

  const handleDelete = (id) => {
    setTableItems((items) => items.filter((item) => item.id !== id));
  };

  return (
    <>
      <Head>
        <title>{currentOrder ? "Order Detail: " + currentOrder.id : "Tovar not found"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentOrder ? (
        <div className={styles["container"]}>
          <div className={styles["orderFilterNav"]}>
            <div>
              <h1 className={styles["pagetitleh1"]}>{`Order ID #${currentOrder.id}`}</h1>
              <p className={styles["pagetitleP"]}>
                <Link href="/orders" style={{ color: '#00B074' }}>Orders /</Link> Order Detail
              </p>
            </div>
            <div className={styles["calendar"]}>
              <button className={styles["cancel"]}>Cancel Order</button>
              <select className={styles["calendar1"]}>
                <option>On Delivery</option>
              </select>
            </div>
          </div>
          <div className={styles["itemSection"]}>
            <div className={styles["aboutUser"]}>
              <div className={styles["aboutUserCard"]}>
                <div
                  style={{
                    width: "160px",
                    height: "160px",
                    background: "gray",
                    borderRadius: "50%",
                    margin: "30px auto",
                  }}
                ></div>
                <p>{currentOrder.customer.name}</p>
                <div>Customer</div>
                <div className={styles["noteOrder"]}>
                  <h2>Note Order</h2>
                  <p style={{ width: '279px' }}>{currentOrder.customer.noteOrder}</p>
                  <div className={styles["manzil"]}>
                    <div
                      style={{
                        width: "49px",
                        height: "49px",
                        background: "white",
                        borderRadius: "50%",
                        margin: "30px 30px",
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center'
                      }}
                    ><Image src="/shipping.png" alt="truck" width={28} height={28} /></div>
                    <p>{currentOrder.customer.manzil}</p>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles["aboutOrders"]}>
              <div className={styles["detailtable1"]}>
                <Table items={tableItems} handleDelete={handleDelete} />
              </div>
              <div className={styles["karta"]}>
                <div className={styles['kartaMap']}>karta</div>
                <p
                  style={{
                    fontSize: "24px",
                    color: "#464255",
                    padding: "0px 0px 10px 30px",
                  }}
                >
                  Delivery by
                </p>
                <div className={styles["aboutDriver"]}>
                  <div className={styles["deliveryBy"]}>
                    <div
                      style={{
                        width: "68px",
                        height: "68px",
                        borderRadius: "50%",
                        background: "gray",
                      }}
                    ></div>
                    <div className={styles["driver"]}>
                      <p style={{ padding: "7px 0px" }}>{currentOrder.deliveredBy.name}</p>
                      <p>ID - {currentOrder.deliveredBy.id}</p>
                    </div>
                  </div>
                  <div className={styles['phoneAndTime']}>
                    <Button title={'Telephone'} phoneNumber={currentOrder.deliveredBy.phone} src={'/phoneIcon.png'} />
                    <Button title={'Delivery Time'} time={currentOrder.deliveredBy.time} src={'/shipping.png'} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div>
          <p>Tovar not found</p>
        </div>
      )}
    </>
  );
}

export default OrderDetail;

function Button(props) {
  const { title, phoneNumber, src, time } = props
  return (
    <button>
      <div>
        <Image style={{ backgroundColor: 'unset' }} src={src} alt="phone" width={26} height={26} />
      </div>
      <div className={styles['numDrAndTime']}>
        <p>{title}</p>
        <p>{phoneNumber} {time}</p>
      </div>
    </button>
  )
}

function Table({ items, handleDelete }) {
  const columns = [
    {
      id: "1",
      name: "Item",
    },
    {
      id: "2",
      name: "Qty",
    },
    {
      id: "3",
      name: "Price",
    },
    {
      id: "4",
      name: "Total Price",
    },
    {
      id: "5",
      name: "",
    },
  ];

  return (
    <table className={styles["detailtable"]}>
      <thead>
        <tr className={styles["tr"]}>
          {columns.map((col) => (
            <th key={col.id} className={styles["userth"]}>
              {col.name}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {items.map((item) => (
          <TableRow key={item.id} item={item} handleDelete={handleDelete} />
        ))}
      </tbody>
    </table>
  );
}

function TableRow(props) {
  const { item, handleDelete } = props;
  return (
    <tr className={styles["usertr"]}>
      <td className={styles["usertd"]}>{item.name}</td>
      <td className={styles["usertd"]}>{item.qty}</td>
      <td className={styles["usertd"]}>{item.price}</td>
      <td className={styles["usertd"]}>{item.price * item.qty}</td>
      <td className={styles["usertd"]}>
        <button
          onClick={() => handleDelete(item.id)}
          style={{
            borderRadius: "50%",
            width: "20px",
            height: "20px",
            border: "1px solid red",
            color: "red",
            background: "unset",
            cursor: "pointer",
          }}
        >
          x
        </button>
      </td>
    </tr>
  );
}

OrderDetail.getLayout = (pageProps) => (
  <MainLayout>
    <OrderDetail {...pageProps} />
  </MainLayout>
);
