import { useParams } from "next/navigation";
import { orderListData } from "@/pages/Data";
import MainLayout from "@/components/common/layouts/MainLayout";
import Orders from "..";
import styles from "@/styles/orderDetail.module.css";
import PageTitle from "../PageTitle2";
import Image from "next/image";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

function OrderDetail() {
  const router = useRouter();
  const route = useParams();
  const orderId = router.query.id;
  const [currentOrder, setCurrentOrder] = useState(null);

  const current = orderListData.find((item) => {
    if (item.id === parseInt(route?.id)) {
      return true;
    }
  });

  const goBack = () => {
    router.push(`/orders/`);
  };

  useEffect(() => {
    if (orderId) {
      const foundOrder = orderListData.find((order) => order.id === orderId);
      setCurrentOrder(foundOrder);
    }
  }, [orderId]);

  return (
    <>
      <Head>
        <title>
          {currentOrder
            ? "Order Detail: " + currentOrder.id
            : "Tovar not found"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentOrder ? (
        <div className={styles["container"]}>
          <div className={styles["orderFilterNav"]}>
            <PageTitle
              title={`Order ID #${current?.id}`}
              subtitle={`Orders / orderDetail`}
            />
            <div className={styles["calendar"]}>
              <button className={styles["cancel"]} onClick={() => goBack()}>
                Cancel Order
              </button>
              <select className={styles["calendar1"]}>
                <option>On Delivery</option>
              </select>
            </div>
          </div>
          <div className={styles["itemSection"]}>
            <div className={styles["aboutUser"]}>
              <div className={styles["aboutUserCard"]}>
                <div
                  style={{
                    width: "160px",
                    height: "160px",
                    background: "gray",
                    borderRadius: "50%",
                    margin: "30px auto",
                  }}
                ></div>
                <p>{current?.customer.name}</p>
                <div>Customer</div>
                <div className={styles["noteOrder"]}>
                  <h2>Note Order</h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua.{" "}
                  </p>
                  <div className={styles["manzil"]}>
                    <div
                      style={{
                        width: "49px",
                        height: "49px",
                        background: "gray",
                        borderRadius: "50%",
                        margin: "30px 30px",
                      }}
                    ></div>
                    <p>6 The Avenue, London EC50 4GN</p>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles["aboutOrders"]}>
              <Table />
              <div className={styles["karta"]}>
                <div></div>
                <p
                  style={{
                    fontSize: "24px",
                    color: "#464255",
                    padding: "0px 0px 30px 30px",
                  }}
                >
                  Delivery by
                </p>
                <div className={styles["aboutDriver"]}>
                  <div>
                    <div>
                      <div
                        style={{
                          width: "68px",
                          height: "68px",
                          borderRadius: "50%",
                          background: "gray",
                        }}
                      ></div>
                      <p style={{ padding: "7px 0px" }}>Kevin Hobs Jr.</p>
                      <p>ID - 412455</p>
                    </div>
                  </div>
                  <div></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div>
          <p>Tovar not found</p>
        </div>
      )}
    </>
  );
}

export default OrderDetail;

function Table() {
  const columns = [
    {
      id: "0",
      name: "Item",
    },
    {
      id: "1",
      name: "Qty",
    },
    {
      id: "2",
      name: "Price",
    },
    {
      id: "3",
      name: "Total Price",
    },
    {
      id: "4",
      name: "",
    },
  ];
  return (
    <table className={styles["detailtable"]}>
      <thead>
        <tr className={styles["tr"]}>
          {columns.map((col) => (
            <TableHead key={col.id} name={col.name} />
          ))}
        </tr>
      </thead>
      <tbody>
        {orderListData.map((item) => (
          <TableRow key={item.items.id} item={item.items} />
        ))}
      </tbody>
    </table>
  );
}

function TableHead({ name }) {
  return <th className={styles["userth"]}>{name}</th>;
}

function TableRow(props) {
  const { item } = props;
  return (
    <>
      {item.map((item) => (
        <tr className={styles["usertr"]}>
          <td className={styles["usertd"]}>item</td>
          <td className={styles["usertd"]}>{item.qty}</td>
          <td className={styles["usertd"]}>{item.price}</td>
          <td className={styles["usertd"]}>{item.price * item.qty}</td>
          <td>
            <button
              style={{
                borderRadius: "50%",
                width: "20px",
                height: "20px",
                border: "1px solid red",
                color: "red",
                background: "unset",
                cursor: "pointer",
              }}
            >
              x
            </button>
          </td>
        </tr>
      ))}
    </>
  );
}

OrderDetail.getLayout = (pageProps) => (
  <MainLayout>
    <OrderDetail {...pageProps} />
  </MainLayout>
);
