import { orderListData as d } from "@/pages/Data";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/orderDetail.module.css";
import PageTitle from "../PageTitle2";
import Image from "next/image";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Link from "next/link";

function OrderDetail() {
  const router = useRouter();
  const [currentOrder, setCurrentOrder] = useState(null);

  useEffect(() => {
    setCurrentOrder(d.find((o) => o.id === router.query.id));
  }, [router]);

  return (
    <>
      <Head>
        <title>{currentOrder ? "Order Detail: " + currentOrder.id : "Tovar not found"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentOrder ? (
        <div className={styles["container"]}>
          <div className={styles["orderFilterNav"]}>
            <div>
              <h1 className={styles["pagetitleh1"]}>{`Order ID #${currentOrder.id}`}</h1>
              <p className={styles["pagetitleP"]}>
                <Link href="/orders">Orders</Link> / Order Detail
              </p>
            </div>
            <div className={styles["calendar"]}>
              <button className={styles["cancel"]}>Cancel Order</button>
              <select className={styles["calendar1"]}>
                <option>On Delivery</option>
              </select>
            </div>
          </div>
          <div className={styles["itemSection"]}>
            <div className={styles["aboutUser"]}>
              <div className={styles["aboutUserCard"]}>
                <div
                  style={{
                    width: "160px",
                    height: "160px",
                    background: "gray",
                    borderRadius: "50%",
                    margin: "30px auto",
                  }}
                ></div>
                <p>{currentOrder.customer.name}</p>
                <div>Customer</div>
                <div className={styles["noteOrder"]}>
                  <h2>Note Order</h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                    incididunt ut labore et dolore magna aliqua.{" "}
                  </p>
                  <div className={styles["manzil"]}>
                    <div
                      style={{
                        width: "49px",
                        height: "49px",
                        background: "gray",
                        borderRadius: "50%",
                        margin: "30px 30px",
                      }}
                    ></div>
                    <p>6 The Avenue, London EC50 4GN</p>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles["aboutOrders"]}>
              <Table items={currentOrder.items} />
              <div className={styles["karta"]}>
                <div></div>
                <p
                  style={{
                    fontSize: "24px",
                    color: "#464255",
                    padding: "0px 0px 30px 30px",
                  }}
                >
                  Delivery by
                </p>
                <div className={styles["aboutDriver"]}>
                  <div>
                    <div>
                      <div
                        style={{
                          width: "68px",
                          height: "68px",
                          borderRadius: "50%",
                          background: "gray",
                        }}
                      ></div>
                      <p style={{ padding: "7px 0px" }}>{currentOrder.deliveredBy.name}</p>
                      <p>ID - 412455</p>
                    </div>
                  </div>
                  <div></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div>
          <p>Tovar not found</p>
        </div>
      )}
    </>
  );
}

export default OrderDetail;

function Table({ items }) {
  const columns = [
    {
      id: "0",
      name: "Item",
    },
    {
      id: "1",
      name: "Qty",
    },
    {
      id: "2",
      name: "Price",
    },
    {
      id: "3",
      name: "Total Price",
    },
    {
      id: "4",
      name: "",
    },
  ];

  return (
    <table className={styles["detailtable"]}>
      <thead>
        <tr className={styles["tr"]}>
          {columns.map((col) => (
            <th key={col.id} className={styles["userth"]}>
              {col.name}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {items.map((item) => (
          <TableRow key={item.id} item={item} />
        ))}
      </tbody>
    </table>
  );
}

function TableRow(props) {
  const { item } = props;
  return (
    <tr className={styles["usertr"]}>
      <td className={styles["usertd"]}>{item.name}</td>
      <td className={styles["usertd"]}>{item.qty}</td>
      <td className={styles["usertd"]}>{item.price}</td>
      <td className={styles["usertd"]}>{item.price * item.qty}</td>
      <td>
        <button
          style={{
            borderRadius: "50%",
            width: "20px",
            height: "20px",
            border: "1px solid red",
            color: "red",
            background: "unset",
            cursor: "pointer",
          }}
        >
          x
        </button>
      </td>
    </tr>
  );
}

OrderDetail.getLayout = (pageProps) => (
  <MainLayout>
    <OrderDetail {...pageProps} />
  </MainLayout>
);
