export const orderListData = [
  {
    id: "765231",
    date: "26 March 2020, 12:42 AM",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    lastAmount: 169.89,
    customer: {
      id: "1",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412455",
      name: "Gudakkina shopir",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "1",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
      {
        id: "2",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "135231",
    date: "26 March 2020, 12:42 AM",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    lastAmount: 169.89,
    customer: {
      id: "2",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412455",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "3",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "325231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    lastAmount: 169.89,
    customer: {
      id: "3",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "112455",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "3",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "555231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    lastAmount: 169.89,
    customer: {
      id: "4",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412459",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "4",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "523231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    lastAmount: 169.89,
    customer: {
      id: "5",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412405",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "5",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "558831",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    lastAmount: 169.89,
    customer: {
      id: "6",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412435",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "6",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "765231",
    date: "26 March 2020, 12:42 AM",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    lastAmount: 169.89,
    customer: {
      id: "1",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412455",
      name: "Gudakkina shopir",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "1",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
      {
        id: "2",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "135231",
    date: "26 March 2020, 12:42 AM",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    lastAmount: 169.89,
    customer: {
      id: "2",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412455",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "3",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "325231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    lastAmount: 169.89,
    customer: {
      id: "3",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "112455",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "3",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "555231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    lastAmount: 169.89,
    customer: {
      id: "4",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412459",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "4",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "523231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    lastAmount: 169.89,
    customer: {
      id: "5",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412405",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "5",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "558831",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    lastAmount: 169.89,
    customer: {
      id: "6",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412435",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "6",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "765231",
    date: "26 March 2020, 12:42 AM",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    lastAmount: 169.89,
    customer: {
      id: "1",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412455",
      name: "Gudakkina shopir",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "1",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
      {
        id: "2",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "135231",
    date: "26 March 2020, 12:42 AM",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    lastAmount: 169.89,
    customer: {
      id: "2",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412455",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "3",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "325231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    lastAmount: 169.89,
    customer: {
      id: "3",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "112455",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "3",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "555231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    lastAmount: 169.89,
    customer: {
      id: "4",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412459",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "4",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "523231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    lastAmount: 169.89,
    customer: {
      id: "5",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412405",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "5",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
  {
    id: "558831",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    lastAmount: 169.89,
    customer: {
      id: "6",
      name: "Mikasa Ackerman",
      noteOrder:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
      manzil: "6 The Avenue, London EC50 4GN",
    },
    deliveredBy: {
      id: "412435",
      name: "Gudakkina",
      phone: "+12 345 5662 66",
      time: "12:52",
    },
    items: [
      {
        id: "6",
        name: "Watermelon juice with ice",
        qty: 5,
        price: 10,
      },
    ],
  },
];

export const customerData = [
  {
    id: 191237,
    name: "Eren Yeager",
    date: "26 March 2020, 12:42 AM",
    job: "UI Designer",
    homeLocation: "St. Kings Road 57th, Garden Hills, Chelsea - London",
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    companyName: "Highspeed Studios",
    totalSpend: 79,
    lastOrder: 119,
    userCard: {
      cardNumber: "2451 2451 2451 2451",
      cardName: "Eren Yeagerjon",
      cardDate: "02/21",
      cardBalans: 9238,
    },
    items: [
      {
        id: 1,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 112.56,
        person: 2,
        min: 12,
      },
      {
        id: 2,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 42.56,
        person: 4,
        min: 22,
      },
      {
        id: 3,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 122.56,
        person: 5,
        min: 24,
      },
    ],
  },
  {
    id: 191238,
    name: "Mikasa Ackerman",
    date: "5 April 2021, 3:14 PM",
    job: "Graphic Designer",
    homeLocation: "Lions Gate 34th, Central City - New York",
    email: "mikasa.ackerman@mail.co.id",
    phone: "+012 345 6790",
    companyName: "Creative Studios",
    totalSpend: 102,
    lastOrder: 120,
    userCard: {
      cardNumber: "2451 2451 2451 2452",
      cardName: "Mikasa Ackerman",
      cardDate: "06/23",
      cardBalans: 11234,
    },
    items: [
      {
        id: 1,
        foodName: "Spicy Grilled Chicken",
        food: "CHICKEN",
        price: 90.0,
        person: 3,
        min: 15,
      },
      {
        id: 2,
        foodName: "Pasta Arrabiata",
        food: "PASTA",
        price: 55.2,
        person: 4,
        min: 18,
      },
    ],
  },
  {
    id: 191239,
    name: "Levi Ackerman",
    date: "18 January 2021, 5:12 PM",
    job: "Project Manager",
    homeLocation: "Oakwood Blvd 20th, Green Town - Toronto",
    email: "levi.ackerman@mail.co.id",
    phone: "+012 345 6791",
    companyName: "FastTech Solutions",
    totalSpend: 150,
    lastOrder: 121,
    userCard: {
      cardNumber: "2451 2451 2451 2453",
      cardName: "Levi Ackerman",
      cardDate: "11/24",
      cardBalans: 8324,
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
  {
    id: 191240,
    name: "Armin Arlert",
    date: "9 September 2022, 10:10 AM",
    job: "Software Developer",
    homeLocation: "Maple Drive 19th, Lakeside - Vancouver",
    email: "armin.arlert@mail.co.id",
    phone: "+012 345 6792",
    companyName: "Tech Innovations",
    totalSpend: 62,
    lastOrder: 122,
    userCard: {
      cardNumber: "2451 2451 2451 2454",
      cardName: "Armin Arlert",
      cardDate: "08/22",
      cardBalans: 6725,
    },
    items: [
      {
        id: 1,
        foodName: "Vegetarian Pizza",
        food: "PIZZA",
        price: 45.99,
        person: 2,
        min: 10,
      },
      {
        id: 2,
        foodName: "Lentil Soup",
        food: "SOUP",
        price: 22.5,
        person: 4,
        min: 16,
      },
    ],
  },
  {
    id: 191241,
    name: "Jean Kirstein",
    date: "10 December 2023, 8:32 AM",
    job: "Marketing Specialist",
    homeLocation: "Ocean View 11th, Seaside - California",
    email: "jean.kirstein@mail.co.id",
    phone: "+012 345 6793",
    companyName: "Sunrise Marketing",
    totalSpend: 55,
    lastOrder: 123,
    userCard: {
      cardNumber: "2451 2451 2451 2455",
      cardName: "Jean Kirstein",
      cardDate: "04/25",
      cardBalans: 5440,
    },
    items: [
      {
        id: 1,
        foodName: "Cheeseburger Deluxe",
        food: "BURGER",
        price: 58.0,
        person: 3,
        min: 12,
      },
    ],
  },
  {
    id: 191237,
    name: "Eren Yeager",
    date: "26 March 2020, 12:42 AM",
    job: "UI Designer",
    homeLocation: "St. Kings Road 57th, Garden Hills, Chelsea - London",
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    companyName: "Highspeed Studios",
    totalSpend: 79,
    lastOrder: 119,
    userCard: {
      cardNumber: "2451 2451 2451 2451",
      cardName: "Eren Yeagerjon",
      cardDate: "02/21",
      cardBalans: 9238,
    },
    items: [
      {
        id: 1,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 112.56,
        person: 2,
        min: 12,
      },
      {
        id: 2,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 42.56,
        person: 4,
        min: 22,
      },
      {
        id: 3,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 122.56,
        person: 5,
        min: 24,
      },
    ],
  },
  {
    id: 191238,
    name: "Mikasa Ackerman",
    date: "5 April 2021, 3:14 PM",
    job: "Graphic Designer",
    homeLocation: "Lions Gate 34th, Central City - New York",
    email: "mikasa.ackerman@mail.co.id",
    phone: "+012 345 6790",
    companyName: "Creative Studios",
    totalSpend: 102,
    lastOrder: 120,
    userCard: {
      cardNumber: "2451 2451 2451 2452",
      cardName: "Mikasa Ackerman",
      cardDate: "06/23",
      cardBalans: 11234,
    },
    items: [
      {
        id: 1,
        foodName: "Spicy Grilled Chicken",
        food: "CHICKEN",
        price: 90.0,
        person: 3,
        min: 15,
      },
      {
        id: 2,
        foodName: "Pasta Arrabiata",
        food: "PASTA",
        price: 55.2,
        person: 4,
        min: 18,
      },
    ],
  },
  {
    id: 191239,
    name: "Levi Ackerman",
    date: "18 January 2021, 5:12 PM",
    job: "Project Manager",
    homeLocation: "Oakwood Blvd 20th, Green Town - Toronto",
    email: "levi.ackerman@mail.co.id",
    phone: "+012 345 6791",
    companyName: "FastTech Solutions",
    totalSpend: 150,
    lastOrder: 121,
    userCard: {
      cardNumber: "2451 2451 2451 2453",
      cardName: "Levi Ackerman",
      cardDate: "11/24",
      cardBalans: 8324,
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
  {
    id: 191240,
    name: "Armin Arlert",
    date: "9 September 2022, 10:10 AM",
    job: "Software Developer",
    homeLocation: "Maple Drive 19th, Lakeside - Vancouver",
    email: "armin.arlert@mail.co.id",
    phone: "+012 345 6792",
    companyName: "Tech Innovations",
    totalSpend: 62,
    lastOrder: 122,
    userCard: {
      cardNumber: "2451 2451 2451 2454",
      cardName: "Armin Arlert",
      cardDate: "08/22",
      cardBalans: 6725,
    },
    items: [
      {
        id: 1,
        foodName: "Vegetarian Pizza",
        food: "PIZZA",
        price: 45.99,
        person: 2,
        min: 10,
      },
      {
        id: 2,
        foodName: "Lentil Soup",
        food: "SOUP",
        price: 22.5,
        person: 4,
        min: 16,
      },
    ],
  },
  {
    id: 191241,
    name: "Jean Kirstein",
    date: "10 December 2023, 8:32 AM",
    job: "Marketing Specialist",
    homeLocation: "Ocean View 11th, Seaside - California",
    email: "jean.kirstein@mail.co.id",
    phone: "+012 345 6793",
    companyName: "Sunrise Marketing",
    totalSpend: 55,
    lastOrder: 123,
    userCard: {
      cardNumber: "2451 2451 2451 2455",
      cardName: "Jean Kirstein",
      cardDate: "04/25",
      cardBalans: 5440,
    },
    items: [
      {
        id: 1,
        foodName: "Cheeseburger Deluxe",
        food: "BURGER",
        price: 58.0,
        person: 3,
        min: 12,
      },
    ],
  },
  {
    id: 191237,
    name: "Eren Yeager",
    date: "26 March 2020, 12:42 AM",
    job: "UI Designer",
    homeLocation: "St. Kings Road 57th, Garden Hills, Chelsea - London",
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    companyName: "Highspeed Studios",
    totalSpend: 79,
    lastOrder: 119,
    userCard: {
      cardNumber: "2451 2451 2451 2451",
      cardName: "Eren Yeagerjon",
      cardDate: "02/21",
      cardBalans: 9238,
    },
    items: [
      {
        id: 1,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 112.56,
        person: 2,
        min: 12,
      },
      {
        id: 2,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 42.56,
        person: 4,
        min: 22,
      },
      {
        id: 3,
        foodName: "Meidum Spicy Spagethi Italiano",
        food: "SPAGETHI",
        price: 122.56,
        person: 5,
        min: 24,
      },
    ],
  },
  {
    id: 191238,
    name: "Mikasa Ackerman",
    date: "5 April 2021, 3:14 PM",
    job: "Graphic Designer",
    homeLocation: "Lions Gate 34th, Central City - New York",
    email: "mikasa.ackerman@mail.co.id",
    phone: "+012 345 6790",
    companyName: "Creative Studios",
    totalSpend: 102,
    lastOrder: 120,
    userCard: {
      cardNumber: "2451 2451 2451 2452",
      cardName: "Mikasa Ackerman",
      cardDate: "06/23",
      cardBalans: 11234,
    },
    items: [
      {
        id: 1,
        foodName: "Spicy Grilled Chicken",
        food: "CHICKEN",
        price: 90.0,
        person: 3,
        min: 15,
      },
      {
        id: 2,
        foodName: "Pasta Arrabiata",
        food: "PASTA",
        price: 55.2,
        person: 4,
        min: 18,
      },
    ],
  },
  {
    id: 191239,
    name: "Levi Ackerman",
    date: "18 January 2021, 5:12 PM",
    job: "Project Manager",
    homeLocation: "Oakwood Blvd 20th, Green Town - Toronto",
    email: "levi.ackerman@mail.co.id",
    phone: "+012 345 6791",
    companyName: "FastTech Solutions",
    totalSpend: 150,
    lastOrder: 121,
    userCard: {
      cardNumber: "2451 2451 2451 2453",
      cardName: "Levi Ackerman",
      cardDate: "11/24",
      cardBalans: 8324,
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
  {
    id: 191240,
    name: "Armin Arlert",
    date: "9 September 2022, 10:10 AM",
    job: "Software Developer",
    homeLocation: "Maple Drive 19th, Lakeside - Vancouver",
    email: "armin.arlert@mail.co.id",
    phone: "+012 345 6792",
    companyName: "Tech Innovations",
    totalSpend: 62,
    lastOrder: 122,
    userCard: {
      cardNumber: "2451 2451 2451 2454",
      cardName: "Armin Arlert",
      cardDate: "08/22",
      cardBalans: 6725,
    },
    items: [
      {
        id: 1,
        foodName: "Vegetarian Pizza",
        food: "PIZZA",
        price: 45.99,
        person: 2,
        min: 10,
      },
      {
        id: 2,
        foodName: "Lentil Soup",
        food: "SOUP",
        price: 22.5,
        person: 4,
        min: 16,
      },
    ],
  },
  {
    id: 191241,
    name: "Jean Kirstein",
    date: "10 December 2023, 8:32 AM",
    job: "Marketing Specialist",
    homeLocation: "Ocean View 11th, Seaside - California",
    email: "jean.kirstein@mail.co.id",
    phone: "+012 345 6793",
    companyName: "Sunrise Marketing",
    totalSpend: 55,
    lastOrder: 123,
    userCard: {
      cardNumber: "2451 2451 2451 2455",
      cardName: "Jean Kirstein",
      cardDate: "04/25",
      cardBalans: 5440,
    },
    items: [
      {
        id: 1,
        foodName: "Cheeseburger Deluxe",
        food: "BURGER",
        price: 58.0,
        person: 3,
        min: 12,
      },
    ],
  },
];
export const foodData = [
  {
    id: "1",
    category: "Food", 
    type: "Burger",
    price: 100,
    name: "Burger Jumbo Special With Spicy",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   minim vLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.eniam,mco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat."
  },
  {
    id: "2",
    category: "Food",
    price: 100,
    type: "pizza",
    name: "Pizza la Piazza Special Nuggets",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   miniLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.m veniam,mco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum dolor sit amLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.et, consectetur adipiscing elit ex ea commodo consequat."
  },
  {
    id: "3",
    category: "Food",
    price: 100,
    type: "Noodle",
    name: "Spicy Mozarella with Barbeque",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   minLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.im veniam,mco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum dolLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.or sit amet, consectetur adipiscing elit ex ea commodo consequat."
  },
  {
    id: "4",
    category: "Drink",
    type: "Sprite",
    price: 100,
    name: "Sprite Flavour with Avocado Juice",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   minLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.im veniam,mco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum doloLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.r sit amet, consectetur adipiscing elit ex ea commodo consequat."
  },
  {
    id: "5",
    category: "Food",
    type: "Burger",
    price: 100,
    name: "Burger Jumbo Special With Spicy",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   minim veniam,mcoLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat. laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum dolor sit amet, consLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.ectetur adipiscing elit ex ea commodo consequat."
  },
  {
    id: "6",
    category: "Food",
    price: 100,
    type: "pizza",
    name: "Pizza la Piazza Special Nuggets",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   minim veniam,mco laboriLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.s nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum dolor sit amet, consectetuLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.r adipiscing elit ex ea commodo consequat."
  },
  {
    id: "7",
    category: "Food",
    price: 100,
    type: "Noodle",
    name: "Spicy Mozarella with Barbeque",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   minim veniam,mco laboris nisiLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat. ut aliquip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum dolor sit amet, consectetur adipLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.iscing elit ex ea commodo consequat."
  },
  {
    id: "8",
    category: "Drink",
    type: "Sprite",
    price: 100,
    name: "Sprite Flavour with Avocado Juice",
    discription: "Lorem ipsum dolor sit amet, consecteunt ut labore et dolore.",
    ingredients: "Lorem ipsum   minim veniam,mco laboris nisi ut aliLorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.quip ex ea commodo consequat.",
    nutritionInfo: "Lorem ipsum dolor sit amet, consectetur adipiscing Lorem ipsum dolor sit amet, consectetur adipiscing elit ex ea commodo consequat.elit ex ea commodo consequat."
  },
];

