import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import { useEffect, useState } from "react";
import { foodData } from "@/Data";
import { useRouter } from "next/router";
export default function FoodDetail() {
  const router = useRouter()
  const [currentFood, setCurrentFood] = useState(null)
  useEffect(() => {
    if (router.query.id) {
      setCurrentFood(
        foodData.find((o) => String(o.id) === router.query.id)
      );
    }
  }, [router]);
  return (
    <>
      <Head>
        <title>Food Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Foods id: {currentFood.id}</div>
    </>
  );
}

FoodDetail.getLayout = (pageProps) => (
  <MainLayout>
    <FoodDetail {...pageProps} />
  </MainLayout>
);
